/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#2f2ebe',
        'surface': '#f7f9fb',
        'secondary': '#006c49',
        'error': '#ba1a1a',
        'on-tertiary-container': '#7073ff',
        'on-surface-variant': '#45464d',
        'surface-container-highest': '#e0e3e5',
        'tertiary-fixed-dim': '#c0c1ff',
        'tertiary': '#000000',
        'on-background': '#191c1e',
        'primary-fixed-dim': '#bec6e0',
        'secondary-fixed': '#6ffbbe',
        'outline': '#76777d',
        'surface-container': '#eceef0',
        'inverse-surface': '#2d3133',
        'on-error-container': '#93000a',
        'secondary-fixed-dim': '#4edea3',
        'primary-fixed': '#dae2fd',
        'surface-dim': '#d8dadc',
        'on-primary': '#ffffff',
        'background': '#f7f9fb',
        'on-primary-container': '#7c839b',
        'on-tertiary': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'on-secondary-fixed': '#002113',
        'on-secondary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#eff1f3',
        'error-container': '#ffdad6',
        'on-secondary-fixed-variant': '#005236',
        'primary': '#000000',
        'on-primary-fixed-variant': '#3f465c',
        'on-error': '#ffffff',
        'outline-variant': '#c6c6cd',
        'surface-tint': '#565e74',
        'surface-bright': '#f7f9fb',
        'tertiary-fixed': '#e1e0ff',
        'on-primary-fixed': '#131b2e',
        'on-secondary-container': '#00714d',
        'on-tertiary-fixed': '#07006c',
        'on-surface': '#191c1e',
        'inverse-primary': '#bec6e0',
        'secondary-container': '#6cf8bb',
        'surface-variant': '#e0e3e5',
        'tertiary-container': '#07006c',
        'surface-container-high': '#e6e8ea',
        'primary-container': '#131b2e',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      spacing: {
        'section-padding': '120px',
        'container-max': '1120px',
        'gutter': '32px',
        'stack-sm': '8px',
        'stack-lg': '32px',
        'stack-md': '16px',
        'unit': '8px',
      },
      fontFamily: {
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
        'label-caps': ['Inter', 'system-ui', 'sans-serif'],
        'h2': ['Manrope', 'system-ui', 'sans-serif'],
        'h3': ['Manrope', 'system-ui', 'sans-serif'],
        'h1': ['Manrope', 'system-ui', 'sans-serif'],
        'body-lg': ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', {
          lineHeight: '1.6',
          letterSpacing: '0',
          fontWeight: '400',
        }],
        'label-caps': ['12px', {
          lineHeight: '1',
          letterSpacing: '0.1em',
          fontWeight: '600',
        }],
        'h2': ['32px', {
          lineHeight: '1.2',
          letterSpacing: '-0.01em',
          fontWeight: '700',
        }],
        'h3': ['24px', {
          lineHeight: '1.3',
          letterSpacing: '0',
          fontWeight: '600',
        }],
        'h1': ['48px', {
          lineHeight: '1.1',
          letterSpacing: '-0.02em',
          fontWeight: '800',
        }],
        'body-lg': ['18px', {
          lineHeight: '1.6',
          letterSpacing: '0',
          fontWeight: '400',
        }],
      },
    },
  },
  plugins: [],
}
